### ISSUE TITLE
google-auth-library dep missing

### ISSUE THREAD

**Issue by Yomguithereal** [iamdustan/blessed-standup#1]
The `google-auth-library` seems to be missing from the package.json file.

**Comment by iamdustan** [comment]
`npm install blessed-standup@0.5.1` :innocent:

**Comment by Yomguithereal** [comment]
Well you were faster than my PR :smile:.

**Comment by iamdustan** [comment]
I tested locally with npm 3 and when I was adding it to our project (with npm2) I hit that right away :)

**Comment by Yomguithereal** [comment]
On a different matter, the package does not refer `eslint` either.

**Comment by iamdustan** [comment]
I am a professional, I swear.
